language: node_js
before_script:
- npm install -g grunt-cli jasmine
services:
- mongodb
env:
- NODE_ENV=test
- CXX=g++-4.8
node_js:
- '0.12'
- '4.1'
deploy:
  provider: heroku
  api_key:
    secure: gPzf/2Ih3g34comqeAS7LgypCEqXHK36GXAm0qmkmPppXR+H5z6S7JM+vXmGCJpCbDo8S4ylHquHBHj+9HVm561YFkfD5tS3bPeYz9/DBNNZ+OLLqeBDSN2SyolxaIWPsPKbek9KzDBMVn/z4QF/g0Lv6/vt6EFxEAAznCAddRHyARlDpDmtyqW27/RARHWuKkVBavy14rr+Ss5GXzmu0fyWA8UjX9umYxLmTGi5ORJVYe9deq92oi6hSadUXQ+Y6q8DpG0uFieCSI6TAHyphh+YSLNXeGpZXuuSxkjtC0b/M//QIULzZKgf4ULgzhVrOiSUShCuerfhUZrUGgN1doG2lBft66whteM3DTaFwCWD7cx/L6DJYGAKt3sN5I7q3UXI5j25APcCtd24q6U4/qgoa+8ik+prBzcg8YKjnLnpDYsO2ic0ehr27J0ZW8VuYA4bnN/CD3IwLHp6fSql4K2Ia2aEkiWa55fgoUAObLxmpH3H86rR264epea43dYIUQc55+XaxCADyt8MvCGBCLfpAyB6za5KW1bENPeTslPmEI6rVoKLIDY0skdyAkm2yAYdkrpKuQVb757r8l/MNer6YThfq3buumx17ygi1ltzkikPqvhZ3RjTZxrecfEzAovWlZXEP2FYCRkn1oqu4DZPBRR+uennqu33hfOIG+4=
  app: logicaladdressd
  on:
    repo: LogicalAddress/logicaladdressd
notifications:
  slack:
    secure: f9MxTGkAz33Jz1BpeS8IZGl5f331nYrhT7tCE/BnzD5rT14g7OEUYBgMy+mJGsbXzaQIM56eWsf6qS945/a2ovYZjfkCPlw5pt0STVaKrONehVN+bSC0YyIPDWyQdppxKQbrj+uo3LtB4DLpaYZEChs14RD1TcgrFKxS1bau+jP/cdPlWQHqEzIKGDs14IgnhBOqFPrBEdX0kf/SNBw1o7FX8t48BS+DA4hjZzgeFFp8MKubvWyOsxlNqIAstnyMBP6oK7HYex1nMcQFqDATgBYLk+V9FZoo4EIcEWoOGp1AuA2ohJkLb6c+gT3BPNprQbnQxyu3GI3X52MjjcTTRY1lARsc2qAk3BytJXfEj6QpQyjLk/24xeKEsIdGl4GvlQ0/Zp7+ByuC7MTScfyWgvM3RfFrpuw+NNc9GxulCTqMMN5dmp1si+1Pd6uc5gTexKJ2D7we7Fk3NV2ujtJTdr451p00glD0Dm71IX4eVdbwdP+WpJsUx2jyckPk/7zVr4Q7J7IXi4C7iwbpelfHWEb28sG8Ha0pSPPogY/I2hQKZjdJLTiNObn9txuZoJt/GDSX1/Db9GCmoO4AY5CCDXm+CX5FJpzm/39aLnYM8Uu0P2pkQsb3jXH283k5NXLSImN4JRRXitwWQf9OySDGJVEINVGve8IjhDDYaXdOAyQ=
